services:
  scraper:
    build: ./aptscraper
    network_mode: host
    command: bash -c 'echo -e "\nusername=${SCRAPYD_USERNAME} \npassword=${SCRAPYD_PASSWORD}" >> "scrapy.cfg"
              && scrapyd-deploy default && python start.py'
    environment:
      USERNAME: ${SCRAPYD_USERNAME}
      PASSWORD: ${SCRAPYD_PASSWORD}
    tty: true
    depends_on:
      - scrapyd

  api:
    build: ./aptapi
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - postgres

  scrapyd:
    build:
      context: ./scrapyd-authenticated
    ports:
      - "6800:6800"
    environment:
        USERNAME: ${SCRAPYD_USERNAME}
        PASSWORD: ${SCRAPYD_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
